# fly.toml app configuration file generated for be8-04-clothing-recommendation-service on 2025-09-03T16:13:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'be8-04-clothing-recommendation-service'
primary_region = 'nrt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
dockerfile = "Dockerfile"